### ISSUE TITLE
Inject accepts module as options

### ISSUE THREAD

**Issue by allevo** [fastify/fastify-accepts#4]
I don't like to have `accepts` as dependency here.

I like a lot the model used in [fastify/point-of-view](https://github.com/fastify/point-of-view).

A peerDependency can help for managing the versions compatibility.

**Comment by delvedor** [comment]
`point-of-view` has a completely different system because of the user choice.

Why put `accepts`as a peer dependency?
Checkout other plugins like [fastify-helmet](https://github.com/fastify/fastify-helmet) or [fastify-mongodb](https://github.com/fastify/fastify-mongodb), they requires a dependency because we are testing them on that dependency, and with [Greenkeeper](https://greenkeeper.io/) we can track breaking changes.

**Comment by mcollina** [comment]
`accepts` is ok to be a dependency here.

**Comment by allevo** [comment]
Good!
